name: RAG chatbot 

on:
  push:
    branches: [main]

jobs:
  build:
      runs-on: ubuntu-22.04

      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Set up python
          uses: actions/setup-python@v5
          with:
            python-version : '3.10'

        - name: Install Dependencies
          run: pip install -r backend/requirements.txt --ignore-requires-python

        - name: Check python version
          run: python --version
            
          
          
